SlnX/webapp2/Models/ErrorViewModel.cs
namespace webapp2.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SlnX/webapp2/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorization.Models;
using Authorization.Interfaces;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace webapp2.Controllers
{
    public class CourseController : Controller
    {

        private readonly ICourseRepository _courseRepository;

        public CourseController(ICourseRepository courseRepository)
        {
            _courseRepository = courseRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            List<Course> courses = _courseRepository.GetAllCourses();
            return View();
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Course course)
        {
            if (course != null)
            {
                _courseRepository.Create(course);

            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                _courseRepository.Delete(id);
            }
            return View();
        }

    }
}

SlnX/webapp2/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using webapp2.Models;

namespace webapp2.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SlnX/webapp2/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorization.Interfaces;
using Authorization.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace webapp2.Controllers
{
    public class RoomController : Controller
    {

        private readonly IRoomRepository _roomRepository;

        public RoomController(IRoomRepository roomRepository)
        {
            _roomRepository = roomRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            List<Room> rooms = _roomRepository.GetAllRooms();
            return View();
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Room room)
        {
            if (room != null)
            {
                _roomRepository.Create(room);

            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                _roomRepository.Delete(id);
            }
            return View();
        }

    }
}

SlnX/webapp2/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorization.Interfaces;
using Authorization.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace webapp2.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;

        public StudentController(IStudentRepository studentRepository)
        {
            _studentRepository = studentRepository;
        }
        //List of students
        [HttpGet]
        public ActionResult Index()
        {
            List<Student> stdList = _studentRepository.GetAllStudents();
            return View(stdList);
        }

        [HttpGet]
        //Render The creation view
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Student student)
        {
            _studentRepository.Create(student);

            List<Student> stdList = _studentRepository.GetAllStudents();
            return View("Index", stdList);
        }

        public ViewResult Delete(int id)
        {
            _studentRepository.Delete(id);

            List<Student> stdList = _studentRepository.GetAllStudents();
            return View("Index", stdList);
        }
        [HttpGet]
        public ActionResult Register()
        {
            return View();

        }
        [HttpPost]
        public ActionResult Register(int studentId, int courseId)
        {
            _studentRepository.Register(studentId, courseId);
            return View();
        }

    }
}

SlnX/webapp2/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorization.Interfaces;
using Authorization.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace webapp2.Controllers
{
    public class TeacherController : Controller
    {

        private readonly ITeacherRepository _teacherRepository;

        public TeacherController(ITeacherRepository teacherRepository)
        {
            _teacherRepository = teacherRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            List<Teacher> teachers = _teacherRepository.GetAllTeachers();
            return View(teachers);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Teacher teacher)
        {
            if (teacher != null)
            {
                _teacherRepository.Create(teacher);

            }
            List<Teacher> teachers = _teacherRepository.GetAllTeachers();
            return View("Index", teachers);
        }

        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                _teacherRepository.Delete(id);
            }
            List<Teacher> teachers = _teacherRepository.GetAllTeachers();
            return View("Index", teachers);
        }

    }
}

SlnX/webapp2/Views/Course/Create.cshtml
@namespace webapp2.Views.Course
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

SlnX/webapp2/Views/Course/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SlnX/webapp2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SlnX/webapp2/Views/Room/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SlnX/webapp2/Views/Room/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SlnX/webapp2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC1.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student"
                               asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher"
                               asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses"
                               asp-action="Index">Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Room</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student"
                               asp-action="Register">Register Sturdent</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

SlnX/webapp2/Views/Student/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>
    .container {
        margin-top: 50px;
    }

    .form-label {
        font-weight: bold;
    }

    .form-check-label {
        font-weight: normal;
    }

    .form-check-input {
        margin-left: 0;
    }
</style>

<body>

    <div class="container">
        <form action="Create" method="post">
            <div class="mb-3">
                <label for="StudentName" class="form-label">Name</label>
                <input type="text" class="form-control" name="StudentName" id="StudentName" placeholder="Your Name">
            </div>
            <div class="mb-3">
                <label for="StudentAge" class="form-label">Age</label>
                <input type="text" class="form-control" name="StudentAge" id="StudentAge" placeholder="Your Age">
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" name="IsActive" id="IsActive" value="true" checked>
                <label class="form-check-label" for="IsActive">Is Active</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

</body>

SlnX/webapp2/Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<Student>

<link rel="stylesheet" href="css/table.css">

<style>
    .styled-table {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 1.2em;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .styled-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid #009879;
            }

    .action-button {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 1em;
        margin-bottom: 20px;
        border-radius: 5px;
        text-decoration: none;
    }

        .action-button:hover {
            background-color: #0056b3;
        }

    .delete-button {
        background-color: #e74c3c;
        color: white;
        border: none;
        padding: 5px 10px;
        cursor: pointer;
        font-size: 0.9em;
        border-radius: 3px;
        text-decoration: none;
    }

        .delete-button:hover {
            background-color: #c0392b;
        }
</style>
<div class="container">

    <a class="action-button" asp-controller="Student" asp-action="Create">Add New Student</a>

    <table class="styled-table">
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Student Age</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var student in Model)
            {
                <tr>
                    <td>@student.StudentName</td>
                    <td>@student.StudentAge</td>
                    <td>
                        <a class="delete-button" asp-controller="Student" asp-action="Delete"
                           asp-route-id="@student.StudentId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

SlnX/webapp2/Views/Student/Registration.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SlnX/webapp2/Views/Teacher/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>
    .container {
        margin-top: 50px;
    }

    .form-label {
        font-weight: bold;
    }

    .form-check-label {
        font-weight: normal;
    }

    .form-check-input {
        margin-left: 0;
    }
</style>

<body>

    <div class="container">
        <form action="Create" method="post">
            <div class="mb-3">
                <label for="TeacherName" class="form-label">Name</label>
                <input type="text" class="form-control" name="TeacherName" id="TeacherName" placeholder="Your Name">
            </div>
            <div class="mb-3">
                <label for="TeacherAge" class="form-label">Age</label>
                <input type="text" class="form-control" name="TeacherAge" id="TeacherAge" placeholder="Your Age">
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" name="IsActive" id="IsActive" value="true" checked>
                <label class="form-check-label" for="IsActive">Is Active</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

</body>

SlnX/webapp2/Views/Teacher/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<Teacher>

<link rel="stylesheet" href="css/table.css">

<style>
    .styled-table {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 1.2em;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .styled-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid #009879;
            }

    .action-button {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 1em;
        margin-bottom: 20px;
        border-radius: 5px;
        text-decoration: none;
    }

        .action-button:hover {
            background-color: #0056b3;
        }

    .delete-button {
        background-color: #e74c3c;
        color: white;
        border: none;
        padding: 5px 10px;
        cursor: pointer;
        font-size: 0.9em;
        border-radius: 3px;
        text-decoration: none;
    }

        .delete-button:hover {
            background-color: #c0392b;
        }
</style>

<div class="container">
    <a class="action-button" asp-controller="Teacher" asp-action="Create">Add New Teacher</a>

    <table class="styled-table">
        <thead>
            <tr>
                <th>Teacher Name</th>
                <th>Teacher Age</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var teacher in Model)
            {
                <tr>
                    <td>@teacher.TeacherName</td>
                    <td>@teacher.TeacherAge</td>
                    <td>
                        <a class="delete-button" asp-controller="Teacher" asp-action="Delete"
                           asp-route-id="@teacher.TeacherId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>